### PR TITLE
Hal ambiq apollo4p pm

### PR DESCRIPTION
**Pull request by RichardSWheatley**
Added sysctrl to CMakeLists.txt for power management

Signed-off-by: Richard Wheatley <richard.wheatley@ambiq.com>

### CODE REVIEW

**Review by fkokosinski — APPROVED** [review]
LGTM. I'll merge this PR when the Zephyr one gets 2 ACKs.

**Comment by RichardSWheatley** [comment]
> LGTM. I'll merge this PR when the Zephyr one gets 2 ACKs.

Once this is approved, do I then go and update the module in the hash west.yaml file of the PR? How is that done?

**Comment by fkokosinski** [comment]
> > LGTM. I'll merge this PR when the Zephyr one gets 2 ACKs.
> 
> Once this is approved, do I then go and update the module in the hash west.yaml file of the PR?

Yup. Once this PR is merged, you'll have to bump the `revision` field in the `west.yml` file so that it matches the commit hash of the latest merge commit in this repo.

**Review by aaronyegx — APPROVED** [review]
Looks good to me. Please help update the HAL revision of corresponding PR. Thanks.

**Pull request merged**
